zookeeper:
  # Zookeeper Server Address, separation with ","
  # EX [ip1:port1,ip2:port2,ip3:port3]
  address: 127.0.0.1:12181
  # Retry Count
  retryCount: 5
  # Retry Interval
  elapsedTimeMs: 5000
  # Session Timeout
  sessionTimeoutMs: 30000
  # Connection Timeout
  connectionTimeoutMs: 10000
